version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/home/suresh/jenkins_data/jenkins_home:/var/jenkins_home"
