# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1346
      MYSQL_ROOT_PASSWORD: 1346

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080